spring:
  datasource:
    url: ${DATASOURCE_URL:jdbc:postgresql://localhost:5432/prms}
    username: ${DATASOURCE_USERNAME:postgres}
    password: ${DATASOURCE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8080

logging:
  level:
    com.tranhuudat.prms: DEBUG
    org.springframework.security: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/prms.log

jwt:
  signer-key: "your-very-strong-secret-key-should-be-at-least-32-chars-long"
  valid-duration: 3600 # in seconds
  refreshable-duration: 86400 # in seconds
